version: "3.7"

# Configuration shared between node services
x-node: &node
  image: ubuntu:eoan-20191101
  volumes:
  - ../target/release/radicle-registry-node:/usr/local/bin/radicle-registry-node:ro
  - ./start-node.sh:/usr/local/bin/start-node.sh:ro
  # Used by the --base-path option
  - /data
  command:
  - /usr/local/bin/start-node.sh

services:
  alice:
    <<: *node
    ports:
    - "9944:9944"
    environment:
      NODE_NAME: alice
  bob:
    <<: *node
    environment:
      NODE_NAME: bob
  charlie:
    <<: *node
    environment:
      NODE_NAME: charlie

  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
    - "9004:3000"
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    - ./grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./grafana-dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus-data:
  grafana-data:
