#!/usr/bin/env bash
#
# Build the node binary including the runtime. Creates
# `./target/release/radicle-registry-node`.

set -euo pipefail

cargo build -p radicle-registry-node --release
(set +o pipefail;  yes | ./target/release/radicle-registry-node purge-chain --chain dev)
echo "Node binary ./target/release/radicle-registry-node was successfully built"
