#!/usr/bin/env bash
#
# Build documentation for client library

set -euo pipefail

cargo doc \
  --no-deps \
  -p radicle-registry-client \
  -p radicle-registry-core \
  -p sp-core \
  -p sp-runtime \
  -p frame-system \
  -p frame-support \
  "$@"
