#!/usr/bin/env bash
#
# Build documentation for client library

set -euo pipefail

cargo doc \
  --no-deps \
  -p radicle-registry-client \
  -p substrate-primitives \
  -p sr-io \
  -p sr-primitives \
  "$@"
