#!/usr/bin/env bash

set -euo pipefail

if [ $# -gt 1 ] || [ "${1-}" = --help ] ; then
  echo "Rebuild runtime-cache/latest.wasm and print a chain spec JSON to the stdout"
  echo "Usage: $0 [<chain>]"
  echo "Default chain: dev"
  exit 1
fi

scripts/build-runtime-wasm runtime-cache/latest.wasm
RUST_LOG=off cargo run -p radicle-registry-node -- build-spec --chain "${1-dev}"
