#!/usr/bin/env bash

set -euo pipefail

export RUST_LOG="${RUST_LOG:-info},substrate_consensus_slots=error,substrate=error"
radicle_registry_node=./target/release/radicle_registry_node
exec $radicle_registry_node "$@" --dev
