#!/usr/bin/env bash
#
# Run dev node with pristine state. Note that we purge the database
# before running the node.

set -euo pipefail

radicle_registry_node=./target/release/radicle_registry_node

((yes | head -n 1) || true) | $radicle_registry_node purge-chain --dev
$radicle_registry_node --dev
