#!/usr/bin/env bash

set -euo pipefail

new_rev="${1:-}"

if [[ -z "$new_rev" ]]; then
  echo "Revision argument is missing"
  echo "Usage: $0 <revision>"
  exit 1
fi

if [[ ! "$new_rev" =~ ^[0-9a-f]{40,40}$ ]]; then
  echo "Invalid revision format"
  exit 1
fi

# Reads `Cargo.lock` and extracts the first revision of the `substrate`
# repo that is used.
function get_substrate_rev () {
  while read -r LINE; do
    if [[ "$LINE" =~ ^\source\ .*git\+https://github\.com/paritytech/substrate.*\?rev=([0-9a-f]{40,40}) ]]; then
      local rev=${BASH_REMATCH[1]}
      if [[ "$rev" != "$new_rev" ]]; then
        echo "${BASH_REMATCH[1]}"
        return
      fi
    fi
  done < Cargo.lock
  echo "Cannot find reference to repository \"https://github.com/paritytech/substrate\" in Cargo.lock" 1>&2
  return 1
}

substrate_rev=$(get_substrate_rev)

sed -i "s/${substrate_rev}/$1/g" -- */Cargo.toml
cargo update
