#!/usr/bin/env bash

set -euo pipefail

if [[ -z "${1:-}" ]]; then
  echo "Revision argument is missing"
  echo "Usage: $0 <revision>"
  exit 1
fi

if [[ ! "${1}" =~ ^[0-9a-f]{40,40}$ ]]; then
  echo "Invalid revision format"
  exit 1
fi

# Reads `Cargo.lock` and extracts the first revision of the `substrate`
# repo that is used.
function get_substrate_rev () {
  while read LINE; do
    if [[ "$LINE" =~ ^\"checksum\ .*git\+https://github\.com/paritytech/substrate.*\?rev=([0-9a-f]{40,40}) ]]; then
      echo ${BASH_REMATCH[1]}
      return
    fi
  done < Cargo.lock
  return 1
}

substrate_rev=$(get_substrate_rev)

sed -i s/${substrate_rev}/$1/g */Cargo.toml
